print("👦🏽: Hola Algodon ")
print('\t🐱: Miau ')
print('\t🐱: Hola, Jose ')
print('👦🏽: Que andas haciendo hoy?') 
print('\t🐱: Pues lo normal, estoy persiguiendo unos cuantos ratones')
print('\t🐱: Y tu? que andas haciendo hoy?')
print('👦🏽: Pues ando aprendiendo diferentes cosas de Python')
print('👦🏽: Es muy interesante las cosas que se pueden hacer con este lenguaje')
print('👦🏽: No te quito mas tu tiempo espero que puedas encontrar muchos ratones')
print('👦🏽: Hasta luego Algodon')
print('\t🐱: Miau, asi lo hare')
print('\t🐱: Hasta luego Jose')