print("👦🏽: Hola Algodón ")
print('\t🐱: Miaw')
print('\t🐱: Miaw')
print('👦🏽: ¿Qué andas haciendo hoy?') 
print('\t🐱: Miaw miaw... miaaaaw')
print('👦🏽: ¿Me preguntas que ando haciendo hoy?')
print('👦🏽: Pues ando aprendiendo diferentes cosas de Python')
print('👦🏽: Es muy interesante las cosas que se pueden hacer con este lenguaje')
print('👦🏽: No te quito más tu tiempo, espero que puedas encontrar muchos ratones')
print('👦🏽: Hasta luego, Algodón')
print('\t🐱: Miaw, miaw!')
print('\t🐱: Miaaaaw')
