numeros = [1.2, 7.3,3.8, 6.78, 5.79, 1, 3, 6, 46, 30]
print("Lista de numeros: ", numeros)
print("|Numero |Tipo de dato\t|")
print('-'*25)
print(f'|{numeros[0]}\t|{type(numeros[0])}|')
print(f'|{numeros[1]}\t|{type(numeros[1])}|')
print(f'|{numeros[2]}\t|{type(numeros[2])}|')
print(f'|{numeros[3]}\t|{type(numeros[3])}|')
print(f'|{numeros[4]}\t|{type(numeros[4])}|')
print(f'|{numeros[5]}\t|{type(numeros[5])}\t|')
print(f'|{numeros[6]}\t|{type(numeros[6])}\t|')
print(f'|{numeros[7]}\t|{type(numeros[7])}\t|')
print(f'|{numeros[8]}\t|{type(numeros[8])}\t|')
print(f'|{numeros[9]}\t|{type(numeros[9])}\t|')